### ISSUE TITLE
VersionUtils.teleport() Paper Server async problem.

### ISSUE THREAD

**Issue by mikechenczy** [Plugily-Projects/MiniGamesBox#54]
I have no idea why the code of teleporting for paper servers is async, howerver, it generates the bug that special items that should be updated into the player's inventory after the teleporting code don't show up when it comes to multiverse. The async codes make the inventory updating too early due to the gap of dimension changing. So if there's no special reason for keeping async for paper servers (the only reason comes to my mind is the optimization), just simply clean the code: `if(isPaper){...}` and only use `entity.teleport(location);`

**Comment by Tigerpanzer02** [comment]
Hey! Did you use the latest development branch for your tests? Or the last release? 
May its already fixed by https://github.com/Plugily-Projects/MiniGamesBox/pull/53

**Comment by mikechenczy** [comment]
I'm sorry that I didn't notice that. Thank you!
